
Analiz <- readXL("C:/Users/mezhebekov/Desktop/regress.xlsx", rownames=FALSE, header=TRUE, na="", 
  sheet="бастапкы деректер (2)", stringsAsFactors=TRUE)
cor(Analiz[,c("x1","x2","x3","x4","x5","x6","x7","x8","x9","y")], use="complete")
scatterplotMatrix(~x1+x2+x3+x4+x5+x6+x7+x8+x9+y, regLine=FALSE, smooth=FALSE, diagonal=list(method="density"), 
  data=Analiz)
RegModel.1 <- lm(y~x1+x2+x3+x4+x5+x6+x7+x8+x9, data=Analiz)
summary(RegModel.1)
RegModel.2 <- lm(y~x2+x5+x6+x7+x8, data=Analiz)
summary(RegModel.2)
library(lattice, pos=16)
summary(RegModel.2)
compareCoefs(RegModel.1, RegModel.2)
Analiz<- within(Analiz, {
  fitted.RegModel.2 <- fitted(RegModel.2)
  residuals.RegModel.2 <- residuals(RegModel.2)
  rstudent.RegModel.2 <- rstudent(RegModel.2)
  hatvalues.RegModel.2 <- hatvalues(RegModel.2)
  cooks.distance.RegModel.2 <- cooks.distance(RegModel.2)
  obsNumber <- 1:nrow(Analiz) 
})
library(MASS, pos=17)
Confint(RegModel.2, level=0.95)
Anova(RegModel.2, type="II")
library(zoo, pos=18)
library(lmtest, pos=18)
dwtest(y ~ x2 + x5 + x6 + x7 + x8, alternative="greater", data=Analiz)
oldpar <- par(oma=c(0,0,3,0), mfrow=c(2,2))
plot(RegModel.2)
par(oldpar)
qqPlot(RegModel.2, simulate=TRUE, id=list(method="y", n=2))
crPlots(RegModel.2, smooth=list(span=0.5))
avPlots(RegModel.2, id=list(method="mahal", n=2))
RegModel.4 <- lm(y~x5+x6+x7+x8, data=Analiz)
summary(RegModel.4)
qqPlot(RegModel.4, simulate=TRUE, id=list(method="y", n=2))
avPlots(RegModel.2, id=list(method="mahal", n=2))
Confint(RegModel.2, level=0.95)
influencePlot(RegModel.2, id=list(method="noteworthy", n=2))
influenceIndexPlot(RegModel.2, id=list(method="y", n=2), vars=c("Cook", "Studentized", "Bonf", "hat"))
plot(allEffects(RegModel.2))
plot(predictorEffects(RegModel.2))
bptest(y ~ x2 + x5 + x6 + x7 + x8, varformula = ~ fitted.values(RegModel.2), studentize=FALSE, data=Analiz)
RegModel.5 <- lm(y~x2+x5, data=Analiz)
summary(RegModel.5)
plot(predictorEffects(RegModel.5))
avPlots(RegModel.5, id=list(method="mahal", n=2))

